apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  replicas: 3  # Number of pods to deploy
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: x69420x/guillermo-ramirez:latest # Replace with your Docker image
        ports:
        - containerPort: 5000

