apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  type: LoadBalancer
  selector:
    app: post-service
  ports:
  - protocol: TCP
    port: 80  # Port exposed externally
    targetPort: 5000  # Port exposed by the container

