name: Build and Publish Docker Image

on:
  push:
    branches:
      - Guillermo-ramirez-1
  pull_request:
    branches:
      - Guillermo-ramirez-1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/Guillermo-Ramirez:latest .

    # Step 4: Push the Docker image
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/Guillermo-Ramirez:latest

